# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ddf/ddf_struct.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ddf import ddf_extensions_pb2 as ddf_dot_ddf__extensions__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x64\x64\x66/ddf_struct.proto\x12\x0b\x64mStructDDF\x1a\x18\x64\x64\x66/ddf_extensions.proto\"|\n\x06Struct\x12/\n\x06\x66ields\x18\x01 \x03(\x0b\x32\x1f.dmStructDDF.Struct.FieldsEntry\x1a\x41\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.dmStructDDF.Value:\x02\x38\x01\"\xba\x01\n\x05Value\x12&\n\x04null\x18\x01 \x01(\x0e\x32\x16.dmStructDDF.NullValueH\x00\x12\x10\n\x06number\x18\x02 \x01(\x01H\x00\x12\x10\n\x06string\x18\x03 \x01(\tH\x00\x12\x0e\n\x04\x62ool\x18\x04 \x01(\x08H\x00\x12%\n\x06struct\x18\x05 \x01(\x0b\x32\x13.dmStructDDF.StructH\x00\x12&\n\x04list\x18\x06 \x01(\x0b\x32\x16.dmStructDDF.ListValueH\x00\x42\x06\n\x04kind\"/\n\tListValue\x12\"\n\x06values\x18\x01 \x03(\x0b\x32\x12.dmStructDDF.Value*\x1b\n\tNullValue\x12\x0e\n\nNULL_VALUE\x10\x00\x42\x1d\n\x10\x63om.dynamo.protoB\tDdfStruct')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ddf.ddf_struct_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\020com.dynamo.protoB\tDdfStruct'
  _STRUCT_FIELDSENTRY._options = None
  _STRUCT_FIELDSENTRY._serialized_options = b'8\001'
  _NULLVALUE._serialized_start=427
  _NULLVALUE._serialized_end=454
  _STRUCT._serialized_start=63
  _STRUCT._serialized_end=187
  _STRUCT_FIELDSENTRY._serialized_start=122
  _STRUCT_FIELDSENTRY._serialized_end=187
  _VALUE._serialized_start=190
  _VALUE._serialized_end=376
  _LISTVALUE._serialized_start=378
  _LISTVALUE._serialized_end=425
# @@protoc_insertion_point(module_scope)
