# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamesys/data_ddf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ddf import ddf_extensions_pb2 as ddf_dot_ddf__extensions__pb2
from ddf import ddf_struct_pb2 as ddf_dot_ddf__struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16gamesys/data_ddf.proto\x12\x0f\x64mGameSystemDDF\x1a\x18\x64\x64\x66/ddf_extensions.proto\x1a\x14\x64\x64\x66/ddf_struct.proto\"6\n\x04\x44\x61ta\x12\x0c\n\x04tags\x18\x01 \x03(\t\x12 \n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x12.dmStructDDF.ValueB%\n\x18\x63om.dynamo.gamesys.protoB\tDataProto')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamesys.data_ddf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.dynamo.gamesys.protoB\tDataProto'
  _DATA._serialized_start=91
  _DATA._serialized_end=145
# @@protoc_insertion_point(module_scope)
