# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamesys/model_ddf.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ddf import ddf_extensions_pb2 as ddf_dot_ddf__extensions__pb2
from ddf import ddf_math_pb2 as ddf_dot_ddf__math__pb2
from graphics import graphics_ddf_pb2 as graphics_dot_graphics__ddf__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17gamesys/model_ddf.proto\x12\ndmModelDDF\x1a\x18\x64\x64\x66/ddf_extensions.proto\x1a\x12\x64\x64\x66/ddf_math.proto\x1a\x1bgraphics/graphics_ddf.proto\"1\n\x07Texture\x12\x0f\n\x07sampler\x18\x01 \x02(\t\x12\x15\n\x07texture\x18\x02 \x02(\tB\x04\xa0\xbb\x18\x01\"\x88\x01\n\x08Material\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x16\n\x08material\x18\x02 \x02(\tB\x04\xa0\xbb\x18\x01\x12%\n\x08textures\x18\x03 \x03(\x0b\x32\x13.dmModelDDF.Texture\x12/\n\nattributes\x18\x04 \x03(\x0b\x32\x1b.dmGraphics.VertexAttribute\"\xf2\x01\n\tModelDesc\x12\x12\n\x04mesh\x18\x02 \x02(\tB\x04\xa0\xbb\x18\x01\x12\x16\n\x08material\x18\x03 \x01(\tB\x04\xa0\xbb\x18\x01\x12\x16\n\x08textures\x18\x04 \x03(\tB\x04\xa0\xbb\x18\x01\x12\x16\n\x08skeleton\x18\x05 \x01(\tB\x04\xa0\xbb\x18\x01\x12\x18\n\nanimations\x18\x06 \x01(\tB\x04\xa0\xbb\x18\x01\x12\x19\n\x11\x64\x65\x66\x61ult_animation\x18\x07 \x01(\t\x12\x0c\n\x04name\x18\n \x01(\t\x12\'\n\tmaterials\x18\x0b \x03(\x0b\x32\x14.dmModelDDF.Material\x12\x1d\n\x0f\x63reate_go_bones\x18\x0c \x01(\x08:\x04true\"}\n\x05Model\x12\x17\n\trig_scene\x18\x01 \x02(\tB\x04\xa0\xbb\x18\x01\x12\x19\n\x11\x64\x65\x66\x61ult_animation\x18\x02 \x01(\t\x12\'\n\tmaterials\x18\x03 \x03(\x0b\x32\x14.dmModelDDF.Material\x12\x17\n\x0f\x63reate_go_bones\x18\x04 \x01(\x08\"\"\n\rResetConstant\x12\x11\n\tname_hash\x18\x01 \x02(\x04\"8\n\nSetTexture\x12\x14\n\x0ctexture_hash\x18\x01 \x02(\x04\x12\x14\n\x0ctexture_unit\x18\x02 \x02(\r\"\x16\n\x14ModelCancelAnimation\"<\n\x12ModelAnimationDone\x12\x14\n\x0c\x61nimation_id\x18\x01 \x02(\x04\x12\x10\n\x08playback\x18\x02 \x02(\rB&\n\x18\x63om.dynamo.gamesys.protoB\nModelProto')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gamesys.model_ddf_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030com.dynamo.gamesys.protoB\nModelProto'
  _TEXTURE.fields_by_name['texture']._options = None
  _TEXTURE.fields_by_name['texture']._serialized_options = b'\240\273\030\001'
  _MATERIAL.fields_by_name['material']._options = None
  _MATERIAL.fields_by_name['material']._serialized_options = b'\240\273\030\001'
  _MODELDESC.fields_by_name['mesh']._options = None
  _MODELDESC.fields_by_name['mesh']._serialized_options = b'\240\273\030\001'
  _MODELDESC.fields_by_name['material']._options = None
  _MODELDESC.fields_by_name['material']._serialized_options = b'\240\273\030\001'
  _MODELDESC.fields_by_name['textures']._options = None
  _MODELDESC.fields_by_name['textures']._serialized_options = b'\240\273\030\001'
  _MODELDESC.fields_by_name['skeleton']._options = None
  _MODELDESC.fields_by_name['skeleton']._serialized_options = b'\240\273\030\001'
  _MODELDESC.fields_by_name['animations']._options = None
  _MODELDESC.fields_by_name['animations']._serialized_options = b'\240\273\030\001'
  _MODEL.fields_by_name['rig_scene']._options = None
  _MODEL.fields_by_name['rig_scene']._serialized_options = b'\240\273\030\001'
  _TEXTURE._serialized_start=114
  _TEXTURE._serialized_end=163
  _MATERIAL._serialized_start=166
  _MATERIAL._serialized_end=302
  _MODELDESC._serialized_start=305
  _MODELDESC._serialized_end=547
  _MODEL._serialized_start=549
  _MODEL._serialized_end=674
  _RESETCONSTANT._serialized_start=676
  _RESETCONSTANT._serialized_end=710
  _SETTEXTURE._serialized_start=712
  _SETTEXTURE._serialized_end=768
  _MODELCANCELANIMATION._serialized_start=770
  _MODELCANCELANIMATION._serialized_end=792
  _MODELANIMATIONDONE._serialized_start=794
  _MODELANIMATIONDONE._serialized_end=854
# @@protoc_insertion_point(module_scope)
